project: dotfiles

# Set this if you want to carry over parent process' environment variables
# carry_env: true

#
# Variables
#
# Feel free to add options here to be used as a variable throughout
# paths.
#
opts:
  region: env:AWS_REGION # you can get env variables with the 'env:' prefix, for default values if env not found use comma. Example: env:AWS_REGION,{DEFAULT_VALUE}
  stage: development

#
# Providers
#
providers:
  # GOOGLE_APPLICATION_CREDENTIALS=foobar.json
  # https://cloud.google.com/secret-manager/docs/reference/libraries#setting_up_authentication
  google_secretmanager:
    kind: google_secretmanager
    maps:
    - id: test
      path: projects/400737752375
      keys:
        CARGO_REGISTRY_TOKEN: cargo_registry_token
        CLOUDFLARE_WORKER_TOKEN: cloudflare_worker_token
        AWS_ACCESS_KEY_ID: cf_aws_access_key_id
        AWS_SECRET_ACCESS_KEY: cf_aws_secret_access_key
        DAGGER_CLOUD_TOKEN: dagger_cloud_token
        DENO_DEPLOY_TOKEN: deno_deploy_token
        HEX_API_KEY: hex_api_key
        MVOLA_CONSUMER_KEY: mvola_consumer_key
        MVOLA_CONSUMER_SECRET: mvola_consumer_secret
        NETLIFY_AUTH_TOKEN: netlify_auth_token
        PULUMI_ACCESS_TOKEN: pulumi_access_token
        SHUTTLE_API_KEY: shuttle_api_key
        SONAR_TOKEN: sonar_token
        SPIN_AUTH_TOKEN: spin_auth_token
        WASMER_TOKEN: wasmer_token
        SSH_PRIVATE_KEY: ssh_private_key
        GPG_PRIVATE_KEY: gpg_private_key
